appName: "" # If Empty the Applications' name will be "<cluster>-common-app"
destNamespace: "" # If Empty the Application destination namespace will be "common-app"
destServer: "" # If Empty the Applications' destination server will be "<cluster>"
repoURL: "" # If Empty the Application source repo will be this repo
srcPath: "" # If Empty the Application source path will be this file's path "essentials/project-1/common-app"
srcTargetRevision: "" # If Empty the Application source target revision will be "HEAD"
autoSync: true # If empty or not set, the Application will be auto-synced
createNamespace: true # If empty or not set, the Application destination namespace will be created if it doesn't exist
additionalSyncOptions: [] # Additional sync options to be added to the Application syncOptions
labels: {} # Additional Application labels
annotations: {} # Additional Application annotations