apiVersion: secrets.crossplane.io/v1alpha1
kind: SecretStore
metadata:
  name: example-vault-secretstore
spec:
  provider:
    apiVersion: vault.upbound.io/v1alpha1
    kind: ProviderConfig
    name: example-vault-provider 