admissionController:
  rbac:
    clusterRole:
      extraResources:
        - apiGroups:
            - "*"
          resources:
            - "*"
          verbs:
            - "*"
backgroundController:
  rbac:
    clusterRole:
      extraResources:
        - apiGroups:
            - "*"
          resources:
            - "*"
          verbs:
            - "*"
